class: pyaml.accelerator.Accelerator
machine: sr
facility: PETRAIII
energy: 6e9
controls:
 - class: tango.pyaml.controlsystem.TangoControlSystem
   tango_host: ebs-simu-3:10000
   name: live
   catalog:
     class: tango.pyaml.tango_catalog.TangoCatalog
     disconnected: True
devices:
- class: pyaml.configuration.template.Template
  name: my_template
  template: |
    class: pyaml.magnet.hcorrector.HCorrector
    name: {sh_name}
    model:
      class: pyaml.magnet.linear_model.LinearMagnetModel
      unit: rad
      hardware_unit: str
      calibration_factor: 1.0
      powerconverter: tango/MAGNET/{sh_name}/B1L
  string_to_replace: "{sh_name}"
  parameter_list:
    - SHI-01
    - SHI-02
    - SHI-03
