# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.0
_src_path: https://github.com/python-accelerator-middle-layer/pyaml-repository-template.git
distribution_name: accelerator-middle-layer
html_title: pyaml
import_name: pyaml
package_name: pyaml
repository_url: https://github.com/python-accelerator-middle-layer/pyaml
use_docs_extra: false
