- type: pyaml.arrays.bpm
  name: BPM
  elements:
    - BPM_001
    - BPM_002
    - BPM_003
    - BPM_004
    - BPM_005
    - BPM_006
    - BPM_007
    - BPM_008
    - BPM_009
    - BPM_010
    - BPM_011
    - BPM_012
    - BPM_013
    - BPM_014
    - BPM_015
    - BPM_016
    - BPM_017
    - BPM_018
    - BPM_019
    - BPM_020
    - BPM_021
    - BPM_022
    - BPM_023
    - BPM_024
    - BPM_025
    - BPM_026
    - BPM_027
    - BPM_028
    - BPM_029
    - BPM_030
    - BPM_031
    - BPM_032
    - BPM_033
    - BPM_034
    - BPM_035
    - BPM_036
    - BPM_037
    - BPM_038
    - BPM_039
    - BPM_040
    - BPM_041
    - BPM_042
    - BPM_043
    - BPM_044
    - BPM_045
    - BPM_046
    - BPM_047
    - BPM_048
    - BPM_049
    - BPM_050
    - BPM_051
    - BPM_052
    - BPM_053
    - BPM_054
    - BPM_055
    - BPM_056
    - BPM_057
    - BPM_058
    - BPM_059
    - BPM_060
    - BPM_061
    - BPM_062
    - BPM_063
    - BPM_064
    - BPM_065
    - BPM_066
    - BPM_067
    - BPM_068
    - BPM_069
    - BPM_070
    - BPM_071
    - BPM_072
    - BPM_073
    - BPM_074
    - BPM_075
    - BPM_076
    - BPM_077
    - BPM_078
    - BPM_079
    - BPM_080
    - BPM_081
    - BPM_082
    - BPM_083
    - BPM_084
    - BPM_085
    - BPM_086
    - BPM_087
    - BPM_088
    - BPM_089
    - BPM_090
    - BPM_091
    - BPM_092
    - BPM_093
    - BPM_094
    - BPM_095
    - BPM_096
    - BPM_097
    - BPM_098
    - BPM_099
    - BPM_100
    - BPM_101
    - BPM_102
    - BPM_103
    - BPM_104
    - BPM_105
    - BPM_106
    - BPM_107
    - BPM_108
    - BPM_109
    - BPM_110
    - BPM_111
    - BPM_112
    - BPM_113
    - BPM_114
    - BPM_115
    - BPM_116
    - BPM_117
    - BPM_118
    - BPM_119
    - BPM_120
    - BPM_121
    - BPM_122
- type: pyaml.arrays.magnet
  name: HCorr
  elements:
    - HCOR_001
    - HCOR_002
    - HCOR_003
    - HCOR_004
    - HCOR_005
    - HCOR_006
    - HCOR_007
    - HCOR_008
    - HCOR_009
    - HCOR_010
    - HCOR_011
    - HCOR_012
    - HCOR_013
    - HCOR_014
    - HCOR_015
    - HCOR_016
    - HCOR_017
    - HCOR_018
    - HCOR_019
    - HCOR_020
    - HCOR_021
    - HCOR_022
    - HCOR_023
    - HCOR_024
    - HCOR_025
    - HCOR_026
    - HCOR_027
    - HCOR_028
    - HCOR_029
    - HCOR_030
    - HCOR_121
    - HCOR_122
    - HCOR_031
    - HCOR_032
    - HCOR_033
    - HCOR_034
    - HCOR_035
    - HCOR_036
    - HCOR_037
    - HCOR_038
    - HCOR_039
    - HCOR_040
    - HCOR_041
    - HCOR_042
    - HCOR_043
    - HCOR_044
    - HCOR_045
    - HCOR_046
    - HCOR_047
    - HCOR_048
    - HCOR_049
    - HCOR_050
    - HCOR_051
    - HCOR_052
    - HCOR_053
    - HCOR_054
    - HCOR_055
    - HCOR_056
    - HCOR_057
    - HCOR_058
    - HCOR_059
    - HCOR_060
    - HCOR_061
    - HCOR_062
    - HCOR_063
    - HCOR_064
    - HCOR_065
    - HCOR_066
    - HCOR_067
    - HCOR_068
    - HCOR_069
    - HCOR_070
    - HCOR_071
    - HCOR_072
    - HCOR_073
    - HCOR_074
    - HCOR_075
    - HCOR_076
    - HCOR_077
    - HCOR_078
    - HCOR_079
    - HCOR_080
    - HCOR_081
    - HCOR_082
    - HCOR_083
    - HCOR_084
    - HCOR_085
    - HCOR_086
    - HCOR_087
    - HCOR_088
    - HCOR_089
    - HCOR_090
    - HCOR_123
    - HCOR_124
    - HCOR_091
    - HCOR_092
    - HCOR_093
    - HCOR_094
    - HCOR_095
    - HCOR_096
    - HCOR_097
    - HCOR_098
    - HCOR_099
    - HCOR_100
    - HCOR_101
    - HCOR_102
    - HCOR_103
    - HCOR_104
    - HCOR_105
    - HCOR_106
    - HCOR_107
    - HCOR_108
    - HCOR_109
    - HCOR_110
    - HCOR_111
    - HCOR_112
    - HCOR_113
    - HCOR_114
    - HCOR_115
    - HCOR_116
    - HCOR_117
    - HCOR_118
    - HCOR_119
    - HCOR_120
- type: pyaml.arrays.magnet
  name: VCorr
  elements:
    - VCOR_001
    - VCOR_002
    - VCOR_003
    - VCOR_004
    - VCOR_005
    - VCOR_006
    - VCOR_007
    - VCOR_008
    - VCOR_009
    - VCOR_010
    - VCOR_011
    - VCOR_012
    - VCOR_013
    - VCOR_014
    - VCOR_015
    - VCOR_016
    - VCOR_017
    - VCOR_018
    - VCOR_019
    - VCOR_020
    - VCOR_021
    - VCOR_022
    - VCOR_023
    - VCOR_024
    - VCOR_025
    - VCOR_026
    - VCOR_027
    - VCOR_028
    - VCOR_029
    - VCOR_030
    - VCOR_121
    - VCOR_122
    - VCOR_031
    - VCOR_032
    - VCOR_033
    - VCOR_034
    - VCOR_035
    - VCOR_036
    - VCOR_037
    - VCOR_038
    - VCOR_039
    - VCOR_040
    - VCOR_041
    - VCOR_042
    - VCOR_043
    - VCOR_044
    - VCOR_045
    - VCOR_046
    - VCOR_047
    - VCOR_048
    - VCOR_049
    - VCOR_050
    - VCOR_051
    - VCOR_052
    - VCOR_053
    - VCOR_054
    - VCOR_055
    - VCOR_056
    - VCOR_057
    - VCOR_058
    - VCOR_059
    - VCOR_060
    - VCOR_061
    - VCOR_062
    - VCOR_063
    - VCOR_064
    - VCOR_065
    - VCOR_066
    - VCOR_067
    - VCOR_068
    - VCOR_069
    - VCOR_070
    - VCOR_071
    - VCOR_072
    - VCOR_073
    - VCOR_074
    - VCOR_075
    - VCOR_076
    - VCOR_077
    - VCOR_078
    - VCOR_079
    - VCOR_080
    - VCOR_081
    - VCOR_082
    - VCOR_083
    - VCOR_084
    - VCOR_085
    - VCOR_086
    - VCOR_087
    - VCOR_088
    - VCOR_089
    - VCOR_090
    - VCOR_123
    - VCOR_124
    - VCOR_091
    - VCOR_092
    - VCOR_093
    - VCOR_094
    - VCOR_095
    - VCOR_096
    - VCOR_097
    - VCOR_098
    - VCOR_099
    - VCOR_100
    - VCOR_101
    - VCOR_102
    - VCOR_103
    - VCOR_104
    - VCOR_105
    - VCOR_106
    - VCOR_107
    - VCOR_108
    - VCOR_109
    - VCOR_110
    - VCOR_111
    - VCOR_112
    - VCOR_113
    - VCOR_114
    - VCOR_115
    - VCOR_116
    - VCOR_117
    - VCOR_118
    - VCOR_119
    - VCOR_120
- type: pyaml.arrays.magnet
  name: FHCORR
  elements:
    - FHCOR_002
    - FHCOR_003
    - FHCOR_004
    - FHCOR_005
    - FHCOR_006
    - FHCOR_007
    - FHCOR_008
    - FHCOR_009
    - FHCOR_010
    - FHCOR_011
    - FHCOR_012
    - FHCOR_013
    - FHCOR_014
    - FHCOR_015
    - FHCOR_016
    - FHCOR_017
    - FHCOR_018
    - FHCOR_019
    - FHCOR_020
    - FHCOR_021
    - FHCOR_022
    - FHCOR_023
    - FHCOR_024
    - FHCOR_025
    - FHCOR_026
    - FHCOR_027
    - FHCOR_028
    - FHCOR_029
    - FHCOR_030
    - FHCOR_031
    - FHCOR_032
    - FHCOR_033
    - FHCOR_034
    - FHCOR_035
    - FHCOR_036
    - FHCOR_037
    - FHCOR_049
    - FHCOR_050
    - FHCOR_038
    - FHCOR_039
    - FHCOR_040
    - FHCOR_041
    - FHCOR_042
    - FHCOR_043
    - FHCOR_044
    - FHCOR_045
    - FHCOR_046
    - FHCOR_047
    - FHCOR_048
    - FHCOR_001
- type: pyaml.arrays.magnet
  name: FVCORR
  elements:
    - FVCOR_001
    - FVCOR_002
    - FVCOR_003
    - FVCOR_004
    - FVCOR_005
    - FVCOR_006
    - FVCOR_007
    - FVCOR_008
    - FVCOR_009
    - FVCOR_010
    - FVCOR_011
    - FVCOR_012
    - FVCOR_013
    - FVCOR_014
    - FVCOR_015
    - FVCOR_016
    - FVCOR_017
    - FVCOR_018
    - FVCOR_019
    - FVCOR_020
    - FVCOR_021
    - FVCOR_022
    - FVCOR_023
    - FVCOR_024
    - FVCOR_025
    - FVCOR_026
    - FVCOR_027
    - FVCOR_028
    - FVCOR_029
    - FVCOR_030
    - FVCOR_031
    - FVCOR_032
    - FVCOR_033
    - FVCOR_034
    - FVCOR_035
    - FVCOR_036
    - FVCOR_049
    - FVCOR_050
    - FVCOR_037
    - FVCOR_038
    - FVCOR_039
    - FVCOR_040
    - FVCOR_041
    - FVCOR_042
    - FVCOR_043
    - FVCOR_044
    - FVCOR_045
    - FVCOR_046
    - FVCOR_047
    - FVCOR_048
- type: pyaml.arrays.magnet
  name: SKEWQUAD
  elements:
    - QT001
    - QT002
    - QT003
    - QT004
    - QT005
    - QT006
    - QT007
    - QT008
    - QT009
    - QT010
    - QT011
    - QT012
    - QT013
    - QT014
    - QT015
    - QT016
    - QT017
    - QT018
    - QT019
    - QT020
    - QT021
    - QT022
    - QT023
    - QT024
    - QT025
    - QT026
    - QT027
    - QT028
    - QT029
    - QT030
    - QT031
    - QT032
    - QT033
    - QT034
    - QT035
    - QT036
    - QT037
    - QT038
    - QT039
    - QT040
    - QT041
    - QT042
    - QT043
    - QT044
    - QT045
    - QT046
    - QT047
    - QT048
    - QT049
    - QT050
    - QT051
    - QT052
    - QT053
    - QT054
    - QT055
    - QT056
    - QT057
    - QT058
    - QT059
    - QT060
    - QT061
    - QT062
    - QT063
    - QT064
    - QT065
    - QT066
    - QT067
    - QT068
    - QT069
    - QT070
    - QT071
    - QT072
    - QT073
    - QT074
    - QT075
    - QT076
    - QT077
    - QT078
    - QT079
    - QT080
    - QT081
    - QT082
    - QT083
    - QT084
    - QT085
    - QT086
    - QT087
    - QT088
    - QT089
    - QT090
    - QT121
    - QT122
    - QT091
    - QT092
    - QT093
    - QT094
    - QT095
    - QT096
    - QT097
    - QT098
    - QT099
    - QT100
    - QT101
    - QT102
    - QT103
    - QT104
    - QT105
    - QT106
    - QT107
    - QT108
    - QT109
    - QT110
    - QT111
    - QT112
    - QT113
    - QT114
    - QT115
    - QT116
    - QT117
    - QT118
    - QT119
    - QT120
- type: pyaml.arrays.magnet
  name: QUAD_Q1
  elements:
    - Q1_001
    - Q1_002
    - Q1_003
    - Q1_004
    - Q1_005
    - Q1_006
    - Q1_007
    - Q1_008
- type: pyaml.arrays.magnet
  name: QUAD_Q2
  elements:
    - Q2_001
    - Q2_002
    - Q2_003
    - Q2_004
    - Q2_005
    - Q2_006
    - Q2_007
    - Q2_008
- type: pyaml.arrays.magnet
  name: QUAD_Q3
  elements:
    - Q3_001
    - Q3_002
    - Q3_003
    - Q3_004
    - Q3_005
    - Q3_006
    - Q3_007
    - Q3_008
- type: pyaml.arrays.magnet
  name: QUAD_Q4
  elements:
    - Q4_001
    - Q4_002
    - Q4_003
    - Q4_004
    - Q4_005
    - Q4_006
    - Q4_007
    - Q4_008
    - Q4_009
    - Q4_010
    - Q4_011
    - Q4_012
    - Q4_013
    - Q4_014
    - Q4_015
    - Q4_016
- type: pyaml.arrays.magnet
  name: QUAD_Q5
  elements:
    - Q5_001
    - Q5_002
    - Q5_003
    - Q5_004
    - Q5_005
    - Q5_006
    - Q5_007
    - Q5_008
    - Q5_009
    - Q5_010
    - Q5_011
    - Q5_012
    - Q5_013
    - Q5_014
    - Q5_015
    - Q5_016
- type: pyaml.arrays.magnet
  name: QUAD_Q6
  elements:
    - Q6_001
    - Q6_002
    - Q6_003
    - Q6_004
    - Q6_005
    - Q6_006
    - Q6_007
    - Q6_008
    - Q6_009
    - Q6_010
    - Q6_011
    - Q6_012
    - Q6_013
    - Q6_014
    - Q6_015
    - Q6_016
    - Q6_017
    - Q6_018
    - Q6_019
    - Q6_020
    - Q6_021
    - Q6_022
    - Q6_023
    - Q6_024
- type: pyaml.arrays.magnet
  name: QUAD_Q7
  elements:
    - Q7_001
    - Q7_002
    - Q7_003
    - Q7_004
    - Q7_005
    - Q7_006
    - Q7_007
    - Q7_008
    - Q7_009
    - Q7_010
    - Q7_011
    - Q7_012
    - Q7_013
    - Q7_014
    - Q7_015
    - Q7_016
    - Q7_017
    - Q7_018
    - Q7_019
    - Q7_020
    - Q7_021
    - Q7_022
    - Q7_023
    - Q7_024
- type: pyaml.arrays.magnet
  name: QUAD_Q8
  elements:
    - Q8_001
    - Q8_002
    - Q8_003
    - Q8_004
    - Q8_005
    - Q8_006
    - Q8_007
    - Q8_008
    - Q8_009
    - Q8_010
    - Q8_011
    - Q8_012
    - Q8_013
    - Q8_014
    - Q8_015
    - Q8_016
    - Q8_017
    - Q8_018
    - Q8_019
    - Q8_020
    - Q8_021
    - Q8_022
    - Q8_023
    - Q8_024
- type: pyaml.arrays.magnet
  name: QUAD_Q9
  elements:
    - Q9_001
    - Q9_002
    - Q9_003
    - Q9_004
    - Q9_005
    - Q9_006
    - Q9_007
    - Q9_008
    - Q9_009
    - Q9_010
    - Q9_011
    - Q9_012
    - Q9_013
    - Q9_014
    - Q9_015
    - Q9_016
- type: pyaml.arrays.magnet
  name: QUAD_Q10
  elements:
    - Q10_001
    - Q10_002
    - Q10_003
    - Q10_004
    - Q10_005
    - Q10_006
    - Q10_007
    - Q10_008
    - Q10_009
    - Q10_010
    - Q10_011
    - Q10_012
    - Q10_013
    - Q10_014
    - Q10_015
    - Q10_016
- type: pyaml.arrays.magnet
  name: QUAD_Q11
  elements:
    - Q11_001
    - Q11_002
- type: pyaml.arrays.magnet
  name: QUAD_Q12
  elements:
    - Q12_001
- type: pyaml.arrays.magnet
  name: QUAD
  elements:
    - Q1_001
    - Q1_002
    - Q1_003
    - Q1_004
    - Q1_005
    - Q1_006
    - Q1_007
    - Q1_008
    - Q2_001
    - Q2_002
    - Q2_003
    - Q2_004
    - Q2_005
    - Q2_006
    - Q2_007
    - Q2_008
    - Q3_001
    - Q3_002
    - Q3_003
    - Q3_004
    - Q3_005
    - Q3_006
    - Q3_007
    - Q3_008
    - Q4_001
    - Q4_002
    - Q4_003
    - Q4_004
    - Q4_005
    - Q4_006
    - Q4_007
    - Q4_008
    - Q4_009
    - Q4_010
    - Q4_011
    - Q4_012
    - Q4_013
    - Q4_014
    - Q4_015
    - Q4_016
    - Q5_001
    - Q5_002
    - Q5_003
    - Q5_004
    - Q5_005
    - Q5_006
    - Q5_007
    - Q5_008
    - Q5_009
    - Q5_010
    - Q5_011
    - Q5_012
    - Q5_013
    - Q5_014
    - Q5_015
    - Q5_016
    - Q6_001
    - Q6_002
    - Q6_003
    - Q6_004
    - Q6_005
    - Q6_006
    - Q6_007
    - Q6_008
    - Q6_009
    - Q6_010
    - Q6_011
    - Q6_012
    - Q6_013
    - Q6_014
    - Q6_015
    - Q6_016
    - Q6_017
    - Q6_018
    - Q6_019
    - Q6_020
    - Q6_021
    - Q6_022
    - Q6_023
    - Q6_024
    - Q7_001
    - Q7_002
    - Q7_003
    - Q7_004
    - Q7_005
    - Q7_006
    - Q7_007
    - Q7_008
    - Q7_009
    - Q7_010
    - Q7_011
    - Q7_012
    - Q7_013
    - Q7_014
    - Q7_015
    - Q7_016
    - Q7_017
    - Q7_018
    - Q7_019
    - Q7_020
    - Q7_021
    - Q7_022
    - Q7_023
    - Q7_024
    - Q8_001
    - Q8_002
    - Q8_003
    - Q8_004
    - Q8_005
    - Q8_006
    - Q8_007
    - Q8_008
    - Q8_009
    - Q8_010
    - Q8_011
    - Q8_012
    - Q8_013
    - Q8_014
    - Q8_015
    - Q8_016
    - Q8_017
    - Q8_018
    - Q8_019
    - Q8_020
    - Q8_021
    - Q8_022
    - Q8_023
    - Q8_024
    - Q9_001
    - Q9_002
    - Q9_003
    - Q9_004
    - Q9_005
    - Q9_006
    - Q9_007
    - Q9_008
    - Q9_009
    - Q9_010
    - Q9_011
    - Q9_012
    - Q9_013
    - Q9_014
    - Q9_015
    - Q9_016
    - Q10_001
    - Q10_002
    - Q10_003
    - Q10_004
    - Q10_005
    - Q10_006
    - Q10_007
    - Q10_008
    - Q10_009
    - Q10_010
    - Q10_011
    - Q10_012
    - Q10_013
    - Q10_014
    - Q10_015
    - Q10_016
    - Q11_001
    - Q11_002
    - Q12_001
- type: pyaml.arrays.magnet
  name: QForTune
  elements:
    - Q7_001
    - Q7_002
    - Q7_003
    - Q7_004
    - Q7_005
    - Q7_006
    - Q7_007
    - Q7_008
    - Q7_009
    - Q7_010
    - Q7_011
    - Q7_012
    - Q7_013
    - Q7_014
    - Q7_015
    - Q7_016
    - Q7_017
    - Q7_018
    - Q7_019
    - Q7_020
    - Q7_021
    - Q7_022
    - Q7_023
    - Q7_024
    - Q9_001
    - Q9_002
    - Q9_003
    - Q9_004
    - Q9_005
    - Q9_006
    - Q9_007
    - Q9_008
    - Q9_009
    - Q9_010
    - Q9_011
    - Q9_012
    - Q9_013
    - Q9_014
    - Q9_015
    - Q9_016
- type: pyaml.arrays.magnet
  name: SEXT
  elements:
    - S1
    - S2
    - S3
    - S4
    - S5
    - S6
    - S7
    - S8
    - S9
    - S10
    - S11
    - S12
- type: pyaml.arrays.magnet
  name: SextForChroma
  elements:
    - S9
    - S10
